/*
===========================================================================

SDL2 OpenGL function loader for RTCW-SP x64

===========================================================================
*/

#include <SDL2/SDL.h>
#include <SDL2/SDL_opengl.h>
#include "../game/q_shared.h"

// Include qgl.h for function pointer types
#include "../renderer/qgl.h"

// Define all qgl function pointers here (they are extern in qgl.h)
// Core OpenGL 1.1 functions
void ( APIENTRY * qglAccum )( GLenum op, GLfloat value );
void ( APIENTRY * qglAlphaFunc )( GLenum func, GLclampf ref );
GLboolean ( APIENTRY * qglAreTexturesResident )( GLsizei n, const GLuint *textures, GLboolean *residences );
void ( APIENTRY * qglArrayElement )( GLint i );
void ( APIENTRY * qglBegin )( GLenum mode );
void ( APIENTRY * qglBindTexture )( GLenum target, GLuint texture );
void ( APIENTRY * qglBitmap )( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap );
void ( APIENTRY * qglBlendFunc )( GLenum sfactor, GLenum dfactor );
void ( APIENTRY * qglCallList )( GLuint list );
void ( APIENTRY * qglCallLists )( GLsizei n, GLenum type, const GLvoid *lists );
void ( APIENTRY * qglClear )( GLbitfield mask );
void ( APIENTRY * qglClearAccum )( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
void ( APIENTRY * qglClearColor )( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha );
void ( APIENTRY * qglClearDepth )( GLclampd depth );
void ( APIENTRY * qglClearIndex )( GLfloat c );
void ( APIENTRY * qglClearStencil )( GLint s );
void ( APIENTRY * qglClipPlane )( GLenum plane, const GLdouble *equation );
void ( APIENTRY * qglColor3b )( GLbyte red, GLbyte green, GLbyte blue );
void ( APIENTRY * qglColor3bv )( const GLbyte *v );
void ( APIENTRY * qglColor3d )( GLdouble red, GLdouble green, GLdouble blue );
void ( APIENTRY * qglColor3dv )( const GLdouble *v );
void ( APIENTRY * qglColor3f )( GLfloat red, GLfloat green, GLfloat blue );
void ( APIENTRY * qglColor3fv )( const GLfloat *v );
void ( APIENTRY * qglColor3i )( GLint red, GLint green, GLint blue );
void ( APIENTRY * qglColor3iv )( const GLint *v );
void ( APIENTRY * qglColor3s )( GLshort red, GLshort green, GLshort blue );
void ( APIENTRY * qglColor3sv )( const GLshort *v );
void ( APIENTRY * qglColor3ub )( GLubyte red, GLubyte green, GLubyte blue );
void ( APIENTRY * qglColor3ubv )( const GLubyte *v );
void ( APIENTRY * qglColor3ui )( GLuint red, GLuint green, GLuint blue );
void ( APIENTRY * qglColor3uiv )( const GLuint *v );
void ( APIENTRY * qglColor3us )( GLushort red, GLushort green, GLushort blue );
void ( APIENTRY * qglColor3usv )( const GLushort *v );
void ( APIENTRY * qglColor4b )( GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha );
void ( APIENTRY * qglColor4bv )( const GLbyte *v );
void ( APIENTRY * qglColor4d )( GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha );
void ( APIENTRY * qglColor4dv )( const GLdouble *v );
void ( APIENTRY * qglColor4f )( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
void ( APIENTRY * qglColor4fv )( const GLfloat *v );
void ( APIENTRY * qglColor4i )( GLint red, GLint green, GLint blue, GLint alpha );
void ( APIENTRY * qglColor4iv )( const GLint *v );
void ( APIENTRY * qglColor4s )( GLshort red, GLshort green, GLshort blue, GLshort alpha );
void ( APIENTRY * qglColor4sv )( const GLshort *v );
void ( APIENTRY * qglColor4ub )( GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha );
void ( APIENTRY * qglColor4ubv )( const GLubyte *v );
void ( APIENTRY * qglColor4ui )( GLuint red, GLuint green, GLuint blue, GLuint alpha );
void ( APIENTRY * qglColor4uiv )( const GLuint *v );
void ( APIENTRY * qglColor4us )( GLushort red, GLushort green, GLushort blue, GLushort alpha );
void ( APIENTRY * qglColor4usv )( const GLushort *v );
void ( APIENTRY * qglColorMask )( GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha );
void ( APIENTRY * qglColorMaterial )( GLenum face, GLenum mode );
void ( APIENTRY * qglColorPointer )( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer );
void ( APIENTRY * qglCopyPixels )( GLint x, GLint y, GLsizei width, GLsizei height, GLenum type );
void ( APIENTRY * qglCopyTexImage1D )( GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border );
void ( APIENTRY * qglCopyTexImage2D )( GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border );
void ( APIENTRY * qglCopyTexSubImage1D )( GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width );
void ( APIENTRY * qglCopyTexSubImage2D )( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height );
void ( APIENTRY * qglCullFace )( GLenum mode );
void ( APIENTRY * qglDeleteLists )( GLuint list, GLsizei range );
void ( APIENTRY * qglDeleteTextures )( GLsizei n, const GLuint *textures );
void ( APIENTRY * qglDepthFunc )( GLenum func );
void ( APIENTRY * qglDepthMask )( GLboolean flag );
void ( APIENTRY * qglDepthRange )( GLclampd zNear, GLclampd zFar );
void ( APIENTRY * qglDisable )( GLenum cap );
void ( APIENTRY * qglDisableClientState )( GLenum array );
void ( APIENTRY * qglDrawArrays )( GLenum mode, GLint first, GLsizei count );
void ( APIENTRY * qglDrawBuffer )( GLenum mode );
void ( APIENTRY * qglDrawElements )( GLenum mode, GLsizei count, GLenum type, const GLvoid *indices );
void ( APIENTRY * qglDrawPixels )( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels );
void ( APIENTRY * qglEdgeFlag )( GLboolean flag );
void ( APIENTRY * qglEdgeFlagPointer )( GLsizei stride, const GLvoid *pointer );
void ( APIENTRY * qglEdgeFlagv )( const GLboolean *flag );
void ( APIENTRY * qglEnable )( GLenum cap );
void ( APIENTRY * qglEnableClientState )( GLenum array );
void ( APIENTRY * qglEnd )( void );
void ( APIENTRY * qglEndList )( void );
void ( APIENTRY * qglEvalCoord1d )( GLdouble u );
void ( APIENTRY * qglEvalCoord1dv )( const GLdouble *u );
void ( APIENTRY * qglEvalCoord1f )( GLfloat u );
void ( APIENTRY * qglEvalCoord1fv )( const GLfloat *u );
void ( APIENTRY * qglEvalCoord2d )( GLdouble u, GLdouble v );
void ( APIENTRY * qglEvalCoord2dv )( const GLdouble *u );
void ( APIENTRY * qglEvalCoord2f )( GLfloat u, GLfloat v );
void ( APIENTRY * qglEvalCoord2fv )( const GLfloat *u );
void ( APIENTRY * qglEvalMesh1 )( GLenum mode, GLint i1, GLint i2 );
void ( APIENTRY * qglEvalMesh2 )( GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2 );
void ( APIENTRY * qglEvalPoint1 )( GLint i );
void ( APIENTRY * qglEvalPoint2 )( GLint i, GLint j );
void ( APIENTRY * qglFeedbackBuffer )( GLsizei size, GLenum type, GLfloat *buffer );
void ( APIENTRY * qglFinish )( void );
void ( APIENTRY * qglFlush )( void );
void ( APIENTRY * qglFogf )( GLenum pname, GLfloat param );
void ( APIENTRY * qglFogfv )( GLenum pname, const GLfloat *params );
void ( APIENTRY * qglFogi )( GLenum pname, GLint param );
void ( APIENTRY * qglFogiv )( GLenum pname, const GLint *params );
void ( APIENTRY * qglFrontFace )( GLenum mode );
void ( APIENTRY * qglFrustum )( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar );
GLuint ( APIENTRY * qglGenLists )( GLsizei range );
void ( APIENTRY * qglGenTextures )( GLsizei n, GLuint *textures );
void ( APIENTRY * qglGetBooleanv )( GLenum pname, GLboolean *params );
void ( APIENTRY * qglGetClipPlane )( GLenum plane, GLdouble *equation );
void ( APIENTRY * qglGetDoublev )( GLenum pname, GLdouble *params );
GLenum ( APIENTRY * qglGetError )( void );
void ( APIENTRY * qglGetFloatv )( GLenum pname, GLfloat *params );
void ( APIENTRY * qglGetIntegerv )( GLenum pname, GLint *params );
void ( APIENTRY * qglGetLightfv )( GLenum light, GLenum pname, GLfloat *params );
void ( APIENTRY * qglGetLightiv )( GLenum light, GLenum pname, GLint *params );
void ( APIENTRY * qglGetMapdv )( GLenum target, GLenum query, GLdouble *v );
void ( APIENTRY * qglGetMapfv )( GLenum target, GLenum query, GLfloat *v );
void ( APIENTRY * qglGetMapiv )( GLenum target, GLenum query, GLint *v );
void ( APIENTRY * qglGetMaterialfv )( GLenum face, GLenum pname, GLfloat *params );
void ( APIENTRY * qglGetMaterialiv )( GLenum face, GLenum pname, GLint *params );
void ( APIENTRY * qglGetPixelMapfv )( GLenum map, GLfloat *values );
void ( APIENTRY * qglGetPixelMapuiv )( GLenum map, GLuint *values );
void ( APIENTRY * qglGetPixelMapusv )( GLenum map, GLushort *values );
void ( APIENTRY * qglGetPointerv )( GLenum pname, GLvoid* *params );
void ( APIENTRY * qglGetPolygonStipple )( GLubyte *mask );
const GLubyte * ( APIENTRY * qglGetString )( GLenum name );
void ( APIENTRY * qglGetTexEnvfv )( GLenum target, GLenum pname, GLfloat *params );
void ( APIENTRY * qglGetTexEnviv )( GLenum target, GLenum pname, GLint *params );
void ( APIENTRY * qglGetTexGendv )( GLenum coord, GLenum pname, GLdouble *params );
void ( APIENTRY * qglGetTexGenfv )( GLenum coord, GLenum pname, GLfloat *params );
void ( APIENTRY * qglGetTexGeniv )( GLenum coord, GLenum pname, GLint *params );
void ( APIENTRY * qglGetTexImage )( GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels );
void ( APIENTRY * qglGetTexParameterfv )( GLenum target, GLenum pname, GLfloat *params );
void ( APIENTRY * qglGetTexParameteriv )( GLenum target, GLenum pname, GLint *params );
void ( APIENTRY * qglHint )( GLenum target, GLenum mode );
void ( APIENTRY * qglIndexMask )( GLuint mask );
void ( APIENTRY * qglIndexPointer )( GLenum type, GLsizei stride, const GLvoid *pointer );
void ( APIENTRY * qglIndexd )( GLdouble c );
void ( APIENTRY * qglIndexdv )( const GLdouble *c );
void ( APIENTRY * qglIndexf )( GLfloat c );
void ( APIENTRY * qglIndexfv )( const GLfloat *c );
void ( APIENTRY * qglIndexi )( GLint c );
void ( APIENTRY * qglIndexiv )( const GLint *c );
void ( APIENTRY * qglIndexs )( GLshort c );
void ( APIENTRY * qglIndexsv )( const GLshort *c );
void ( APIENTRY * qglIndexub )( GLubyte c );
void ( APIENTRY * qglIndexubv )( const GLubyte *c );
void ( APIENTRY * qglInitNames )( void );
void ( APIENTRY * qglInterleavedArrays )( GLenum format, GLsizei stride, const GLvoid *pointer );
GLboolean ( APIENTRY * qglIsEnabled )( GLenum cap );
GLboolean ( APIENTRY * qglIsList )( GLuint list );
GLboolean ( APIENTRY * qglIsTexture )( GLuint texture );
void ( APIENTRY * qglLightModelf )( GLenum pname, GLfloat param );
void ( APIENTRY * qglLightModelfv )( GLenum pname, const GLfloat *params );
void ( APIENTRY * qglLightModeli )( GLenum pname, GLint param );
void ( APIENTRY * qglLightModeliv )( GLenum pname, const GLint *params );
void ( APIENTRY * qglLightf )( GLenum light, GLenum pname, GLfloat param );
void ( APIENTRY * qglLightfv )( GLenum light, GLenum pname, const GLfloat *params );
void ( APIENTRY * qglLighti )( GLenum light, GLenum pname, GLint param );
void ( APIENTRY * qglLightiv )( GLenum light, GLenum pname, const GLint *params );
void ( APIENTRY * qglLineStipple )( GLint factor, GLushort pattern );
void ( APIENTRY * qglLineWidth )( GLfloat width );
void ( APIENTRY * qglListBase )( GLuint base );
void ( APIENTRY * qglLoadIdentity )( void );
void ( APIENTRY * qglLoadMatrixd )( const GLdouble *m );
void ( APIENTRY * qglLoadMatrixf )( const GLfloat *m );
void ( APIENTRY * qglLoadName )( GLuint name );
void ( APIENTRY * qglLogicOp )( GLenum opcode );
void ( APIENTRY * qglMap1d )( GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points );
void ( APIENTRY * qglMap1f )( GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points );
void ( APIENTRY * qglMap2d )( GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points );
void ( APIENTRY * qglMap2f )( GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points );
void ( APIENTRY * qglMapGrid1d )( GLint un, GLdouble u1, GLdouble u2 );
void ( APIENTRY * qglMapGrid1f )( GLint un, GLfloat u1, GLfloat u2 );
void ( APIENTRY * qglMapGrid2d )( GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2 );
void ( APIENTRY * qglMapGrid2f )( GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2 );
void ( APIENTRY * qglMaterialf )( GLenum face, GLenum pname, GLfloat param );
void ( APIENTRY * qglMaterialfv )( GLenum face, GLenum pname, const GLfloat *params );
void ( APIENTRY * qglMateriali )( GLenum face, GLenum pname, GLint param );
void ( APIENTRY * qglMaterialiv )( GLenum face, GLenum pname, const GLint *params );
void ( APIENTRY * qglMatrixMode )( GLenum mode );
void ( APIENTRY * qglMultMatrixd )( const GLdouble *m );
void ( APIENTRY * qglMultMatrixf )( const GLfloat *m );
void ( APIENTRY * qglNewList )( GLuint list, GLenum mode );
void ( APIENTRY * qglNormal3b )( GLbyte nx, GLbyte ny, GLbyte nz );
void ( APIENTRY * qglNormal3bv )( const GLbyte *v );
void ( APIENTRY * qglNormal3d )( GLdouble nx, GLdouble ny, GLdouble nz );
void ( APIENTRY * qglNormal3dv )( const GLdouble *v );
void ( APIENTRY * qglNormal3f )( GLfloat nx, GLfloat ny, GLfloat nz );
void ( APIENTRY * qglNormal3fv )( const GLfloat *v );
void ( APIENTRY * qglNormal3i )( GLint nx, GLint ny, GLint nz );
void ( APIENTRY * qglNormal3iv )( const GLint *v );
void ( APIENTRY * qglNormal3s )( GLshort nx, GLshort ny, GLshort nz );
void ( APIENTRY * qglNormal3sv )( const GLshort *v );
void ( APIENTRY * qglNormalPointer )( GLenum type, GLsizei stride, const GLvoid *pointer );
void ( APIENTRY * qglOrtho )( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar );
void ( APIENTRY * qglPassThrough )( GLfloat token );
void ( APIENTRY * qglPixelMapfv )( GLenum map, GLsizei mapsize, const GLfloat *values );
void ( APIENTRY * qglPixelMapuiv )( GLenum map, GLsizei mapsize, const GLuint *values );
void ( APIENTRY * qglPixelMapusv )( GLenum map, GLsizei mapsize, const GLushort *values );
void ( APIENTRY * qglPixelStoref )( GLenum pname, GLfloat param );
void ( APIENTRY * qglPixelStorei )( GLenum pname, GLint param );
void ( APIENTRY * qglPixelTransferf )( GLenum pname, GLfloat param );
void ( APIENTRY * qglPixelTransferi )( GLenum pname, GLint param );
void ( APIENTRY * qglPixelZoom )( GLfloat xfactor, GLfloat yfactor );
void ( APIENTRY * qglPointSize )( GLfloat size );
void ( APIENTRY * qglPolygonMode )( GLenum face, GLenum mode );
void ( APIENTRY * qglPolygonOffset )( GLfloat factor, GLfloat units );
void ( APIENTRY * qglPolygonStipple )( const GLubyte *mask );
void ( APIENTRY * qglPopAttrib )( void );
void ( APIENTRY * qglPopClientAttrib )( void );
void ( APIENTRY * qglPopMatrix )( void );
void ( APIENTRY * qglPopName )( void );
void ( APIENTRY * qglPrioritizeTextures )( GLsizei n, const GLuint *textures, const GLclampf *priorities );
void ( APIENTRY * qglPushAttrib )( GLbitfield mask );
void ( APIENTRY * qglPushClientAttrib )( GLbitfield mask );
void ( APIENTRY * qglPushMatrix )( void );
void ( APIENTRY * qglPushName )( GLuint name );
void ( APIENTRY * qglRasterPos2d )( GLdouble x, GLdouble y );
void ( APIENTRY * qglRasterPos2dv )( const GLdouble *v );
void ( APIENTRY * qglRasterPos2f )( GLfloat x, GLfloat y );
void ( APIENTRY * qglRasterPos2fv )( const GLfloat *v );
void ( APIENTRY * qglRasterPos2i )( GLint x, GLint y );
void ( APIENTRY * qglRasterPos2iv )( const GLint *v );
void ( APIENTRY * qglRasterPos2s )( GLshort x, GLshort y );
void ( APIENTRY * qglRasterPos2sv )( const GLshort *v );
void ( APIENTRY * qglRasterPos3d )( GLdouble x, GLdouble y, GLdouble z );
void ( APIENTRY * qglRasterPos3dv )( const GLdouble *v );
void ( APIENTRY * qglRasterPos3f )( GLfloat x, GLfloat y, GLfloat z );
void ( APIENTRY * qglRasterPos3fv )( const GLfloat *v );
void ( APIENTRY * qglRasterPos3i )( GLint x, GLint y, GLint z );
void ( APIENTRY * qglRasterPos3iv )( const GLint *v );
void ( APIENTRY * qglRasterPos3s )( GLshort x, GLshort y, GLshort z );
void ( APIENTRY * qglRasterPos3sv )( const GLshort *v );
void ( APIENTRY * qglRasterPos4d )( GLdouble x, GLdouble y, GLdouble z, GLdouble w );
void ( APIENTRY * qglRasterPos4dv )( const GLdouble *v );
void ( APIENTRY * qglRasterPos4f )( GLfloat x, GLfloat y, GLfloat z, GLfloat w );
void ( APIENTRY * qglRasterPos4fv )( const GLfloat *v );
void ( APIENTRY * qglRasterPos4i )( GLint x, GLint y, GLint z, GLint w );
void ( APIENTRY * qglRasterPos4iv )( const GLint *v );
void ( APIENTRY * qglRasterPos4s )( GLshort x, GLshort y, GLshort z, GLshort w );
void ( APIENTRY * qglRasterPos4sv )( const GLshort *v );
void ( APIENTRY * qglReadBuffer )( GLenum mode );
void ( APIENTRY * qglReadPixels )( GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels );
void ( APIENTRY * qglRectd )( GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2 );
void ( APIENTRY * qglRectdv )( const GLdouble *v1, const GLdouble *v2 );
void ( APIENTRY * qglRectf )( GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2 );
void ( APIENTRY * qglRectfv )( const GLfloat *v1, const GLfloat *v2 );
void ( APIENTRY * qglRecti )( GLint x1, GLint y1, GLint x2, GLint y2 );
void ( APIENTRY * qglRectiv )( const GLint *v1, const GLint *v2 );
void ( APIENTRY * qglRects )( GLshort x1, GLshort y1, GLshort x2, GLshort y2 );
void ( APIENTRY * qglRectsv )( const GLshort *v1, const GLshort *v2 );
GLint ( APIENTRY * qglRenderMode )( GLenum mode );
void ( APIENTRY * qglRotated )( GLdouble angle, GLdouble x, GLdouble y, GLdouble z );
void ( APIENTRY * qglRotatef )( GLfloat angle, GLfloat x, GLfloat y, GLfloat z );
void ( APIENTRY * qglScaled )( GLdouble x, GLdouble y, GLdouble z );
void ( APIENTRY * qglScalef )( GLfloat x, GLfloat y, GLfloat z );
void ( APIENTRY * qglScissor )( GLint x, GLint y, GLsizei width, GLsizei height );
void ( APIENTRY * qglSelectBuffer )( GLsizei size, GLuint *buffer );
void ( APIENTRY * qglShadeModel )( GLenum mode );
void ( APIENTRY * qglStencilFunc )( GLenum func, GLint ref, GLuint mask );
void ( APIENTRY * qglStencilMask )( GLuint mask );
void ( APIENTRY * qglStencilOp )( GLenum fail, GLenum zfail, GLenum zpass );
void ( APIENTRY * qglTexCoord1d )( GLdouble s );
void ( APIENTRY * qglTexCoord1dv )( const GLdouble *v );
void ( APIENTRY * qglTexCoord1f )( GLfloat s );
void ( APIENTRY * qglTexCoord1fv )( const GLfloat *v );
void ( APIENTRY * qglTexCoord1i )( GLint s );
void ( APIENTRY * qglTexCoord1iv )( const GLint *v );
void ( APIENTRY * qglTexCoord1s )( GLshort s );
void ( APIENTRY * qglTexCoord1sv )( const GLshort *v );
void ( APIENTRY * qglTexCoord2d )( GLdouble s, GLdouble t );
void ( APIENTRY * qglTexCoord2dv )( const GLdouble *v );
void ( APIENTRY * qglTexCoord2f )( GLfloat s, GLfloat t );
void ( APIENTRY * qglTexCoord2fv )( const GLfloat *v );
void ( APIENTRY * qglTexCoord2i )( GLint s, GLint t );
void ( APIENTRY * qglTexCoord2iv )( const GLint *v );
void ( APIENTRY * qglTexCoord2s )( GLshort s, GLshort t );
void ( APIENTRY * qglTexCoord2sv )( const GLshort *v );
void ( APIENTRY * qglTexCoord3d )( GLdouble s, GLdouble t, GLdouble r );
void ( APIENTRY * qglTexCoord3dv )( const GLdouble *v );
void ( APIENTRY * qglTexCoord3f )( GLfloat s, GLfloat t, GLfloat r );
void ( APIENTRY * qglTexCoord3fv )( const GLfloat *v );
void ( APIENTRY * qglTexCoord3i )( GLint s, GLint t, GLint r );
void ( APIENTRY * qglTexCoord3iv )( const GLint *v );
void ( APIENTRY * qglTexCoord3s )( GLshort s, GLshort t, GLshort r );
void ( APIENTRY * qglTexCoord3sv )( const GLshort *v );
void ( APIENTRY * qglTexCoord4d )( GLdouble s, GLdouble t, GLdouble r, GLdouble q );
void ( APIENTRY * qglTexCoord4dv )( const GLdouble *v );
void ( APIENTRY * qglTexCoord4f )( GLfloat s, GLfloat t, GLfloat r, GLfloat q );
void ( APIENTRY * qglTexCoord4fv )( const GLfloat *v );
void ( APIENTRY * qglTexCoord4i )( GLint s, GLint t, GLint r, GLint q );
void ( APIENTRY * qglTexCoord4iv )( const GLint *v );
void ( APIENTRY * qglTexCoord4s )( GLshort s, GLshort t, GLshort r, GLshort q );
void ( APIENTRY * qglTexCoord4sv )( const GLshort *v );
void ( APIENTRY * qglTexCoordPointer )( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer );
void ( APIENTRY * qglTexEnvf )( GLenum target, GLenum pname, GLfloat param );
void ( APIENTRY * qglTexEnvfv )( GLenum target, GLenum pname, const GLfloat *params );
void ( APIENTRY * qglTexEnvi )( GLenum target, GLenum pname, GLint param );
void ( APIENTRY * qglTexEnviv )( GLenum target, GLenum pname, const GLint *params );
void ( APIENTRY * qglTexGend )( GLenum coord, GLenum pname, GLdouble param );
void ( APIENTRY * qglTexGendv )( GLenum coord, GLenum pname, const GLdouble *params );
void ( APIENTRY * qglTexGenf )( GLenum coord, GLenum pname, GLfloat param );
void ( APIENTRY * qglTexGenfv )( GLenum coord, GLenum pname, const GLfloat *params );
void ( APIENTRY * qglTexGeni )( GLenum coord, GLenum pname, GLint param );
void ( APIENTRY * qglTexGeniv )( GLenum coord, GLenum pname, const GLint *params );
void ( APIENTRY * qglTexImage1D )( GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels );
void ( APIENTRY * qglTexImage2D )( GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels );
void ( APIENTRY * qglTexParameterf )( GLenum target, GLenum pname, GLfloat param );
void ( APIENTRY * qglTexParameterfv )( GLenum target, GLenum pname, const GLfloat *params );
void ( APIENTRY * qglTexParameteri )( GLenum target, GLenum pname, GLint param );
void ( APIENTRY * qglTexParameteriv )( GLenum target, GLenum pname, const GLint *params );
void ( APIENTRY * qglTexSubImage1D )( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels );
void ( APIENTRY * qglTexSubImage2D )( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels );
void ( APIENTRY * qglTranslated )( GLdouble x, GLdouble y, GLdouble z );
void ( APIENTRY * qglTranslatef )( GLfloat x, GLfloat y, GLfloat z );
void ( APIENTRY * qglVertex2d )( GLdouble x, GLdouble y );
void ( APIENTRY * qglVertex2dv )( const GLdouble *v );
void ( APIENTRY * qglVertex2f )( GLfloat x, GLfloat y );
void ( APIENTRY * qglVertex2fv )( const GLfloat *v );
void ( APIENTRY * qglVertex2i )( GLint x, GLint y );
void ( APIENTRY * qglVertex2iv )( const GLint *v );
void ( APIENTRY * qglVertex2s )( GLshort x, GLshort y );
void ( APIENTRY * qglVertex2sv )( const GLshort *v );
void ( APIENTRY * qglVertex3d )( GLdouble x, GLdouble y, GLdouble z );
void ( APIENTRY * qglVertex3dv )( const GLdouble *v );
void ( APIENTRY * qglVertex3f )( GLfloat x, GLfloat y, GLfloat z );
void ( APIENTRY * qglVertex3fv )( const GLfloat *v );
void ( APIENTRY * qglVertex3i )( GLint x, GLint y, GLint z );
void ( APIENTRY * qglVertex3iv )( const GLint *v );
void ( APIENTRY * qglVertex3s )( GLshort x, GLshort y, GLshort z );
void ( APIENTRY * qglVertex3sv )( const GLshort *v );
void ( APIENTRY * qglVertex4d )( GLdouble x, GLdouble y, GLdouble z, GLdouble w );
void ( APIENTRY * qglVertex4dv )( const GLdouble *v );
void ( APIENTRY * qglVertex4f )( GLfloat x, GLfloat y, GLfloat z, GLfloat w );
void ( APIENTRY * qglVertex4fv )( const GLfloat *v );
void ( APIENTRY * qglVertex4i )( GLint x, GLint y, GLint z, GLint w );
void ( APIENTRY * qglVertex4iv )( const GLint *v );
void ( APIENTRY * qglVertex4s )( GLshort x, GLshort y, GLshort z, GLshort w );
void ( APIENTRY * qglVertex4sv )( const GLshort *v );
void ( APIENTRY * qglVertexPointer )( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer );
void ( APIENTRY * qglViewport )( GLint x, GLint y, GLsizei width, GLsizei height );

// Extension functions (also declared in tr_init.c, but defined here for SDL2 build)
void ( APIENTRY * qglMultiTexCoord2fARB )( GLenum texture, GLfloat s, GLfloat t );
void ( APIENTRY * qglActiveTextureARB )( GLenum texture );
void ( APIENTRY * qglClientActiveTextureARB )( GLenum texture );
void ( APIENTRY * qglLockArraysEXT )( GLint, GLint );
void ( APIENTRY * qglUnlockArraysEXT )( void );
void ( APIENTRY * qglPNTrianglesiATI )( GLenum pname, GLint param );
void ( APIENTRY * qglPNTrianglesfATI )( GLenum pname, GLfloat param );

// Define all qgl function pointers
// This file provides QGL_SDL_Init() which loads GL functions via SDL_GL_GetProcAddress

#define SDL_GPA( a ) SDL_GL_GetProcAddress( a )

qboolean QGL_SDL_Init( void ) {
    // Core OpenGL 1.1 functions
    qglAccum                     = SDL_GPA( "glAccum" );
    qglAlphaFunc                 = SDL_GPA( "glAlphaFunc" );
    qglAreTexturesResident       = SDL_GPA( "glAreTexturesResident" );
    qglArrayElement              = SDL_GPA( "glArrayElement" );
    qglBegin                     = SDL_GPA( "glBegin" );
    qglBindTexture               = SDL_GPA( "glBindTexture" );
    qglBitmap                    = SDL_GPA( "glBitmap" );
    qglBlendFunc                 = SDL_GPA( "glBlendFunc" );
    qglCallList                  = SDL_GPA( "glCallList" );
    qglCallLists                 = SDL_GPA( "glCallLists" );
    qglClear                     = SDL_GPA( "glClear" );
    qglClearAccum                = SDL_GPA( "glClearAccum" );
    qglClearColor                = SDL_GPA( "glClearColor" );
    qglClearDepth                = SDL_GPA( "glClearDepth" );
    qglClearIndex                = SDL_GPA( "glClearIndex" );
    qglClearStencil              = SDL_GPA( "glClearStencil" );
    qglClipPlane                 = SDL_GPA( "glClipPlane" );
    qglColor3b                   = SDL_GPA( "glColor3b" );
    qglColor3bv                  = SDL_GPA( "glColor3bv" );
    qglColor3d                   = SDL_GPA( "glColor3d" );
    qglColor3dv                  = SDL_GPA( "glColor3dv" );
    qglColor3f                   = SDL_GPA( "glColor3f" );
    qglColor3fv                  = SDL_GPA( "glColor3fv" );
    qglColor3i                   = SDL_GPA( "glColor3i" );
    qglColor3iv                  = SDL_GPA( "glColor3iv" );
    qglColor3s                   = SDL_GPA( "glColor3s" );
    qglColor3sv                  = SDL_GPA( "glColor3sv" );
    qglColor3ub                  = SDL_GPA( "glColor3ub" );
    qglColor3ubv                 = SDL_GPA( "glColor3ubv" );
    qglColor3ui                  = SDL_GPA( "glColor3ui" );
    qglColor3uiv                 = SDL_GPA( "glColor3uiv" );
    qglColor3us                  = SDL_GPA( "glColor3us" );
    qglColor3usv                 = SDL_GPA( "glColor3usv" );
    qglColor4b                   = SDL_GPA( "glColor4b" );
    qglColor4bv                  = SDL_GPA( "glColor4bv" );
    qglColor4d                   = SDL_GPA( "glColor4d" );
    qglColor4dv                  = SDL_GPA( "glColor4dv" );
    qglColor4f                   = SDL_GPA( "glColor4f" );
    qglColor4fv                  = SDL_GPA( "glColor4fv" );
    qglColor4i                   = SDL_GPA( "glColor4i" );
    qglColor4iv                  = SDL_GPA( "glColor4iv" );
    qglColor4s                   = SDL_GPA( "glColor4s" );
    qglColor4sv                  = SDL_GPA( "glColor4sv" );
    qglColor4ub                  = SDL_GPA( "glColor4ub" );
    qglColor4ubv                 = SDL_GPA( "glColor4ubv" );
    qglColor4ui                  = SDL_GPA( "glColor4ui" );
    qglColor4uiv                 = SDL_GPA( "glColor4uiv" );
    qglColor4us                  = SDL_GPA( "glColor4us" );
    qglColor4usv                 = SDL_GPA( "glColor4usv" );
    qglColorMask                 = SDL_GPA( "glColorMask" );
    qglColorMaterial             = SDL_GPA( "glColorMaterial" );
    qglColorPointer              = SDL_GPA( "glColorPointer" );
    qglCopyPixels                = SDL_GPA( "glCopyPixels" );
    qglCopyTexImage1D            = SDL_GPA( "glCopyTexImage1D" );
    qglCopyTexImage2D            = SDL_GPA( "glCopyTexImage2D" );
    qglCopyTexSubImage1D         = SDL_GPA( "glCopyTexSubImage1D" );
    qglCopyTexSubImage2D         = SDL_GPA( "glCopyTexSubImage2D" );
    qglCullFace                  = SDL_GPA( "glCullFace" );
    qglDeleteLists               = SDL_GPA( "glDeleteLists" );
    qglDeleteTextures            = SDL_GPA( "glDeleteTextures" );
    qglDepthFunc                 = SDL_GPA( "glDepthFunc" );
    qglDepthMask                 = SDL_GPA( "glDepthMask" );
    qglDepthRange                = SDL_GPA( "glDepthRange" );
    qglDisable                   = SDL_GPA( "glDisable" );
    qglDisableClientState        = SDL_GPA( "glDisableClientState" );
    qglDrawArrays                = SDL_GPA( "glDrawArrays" );
    qglDrawBuffer                = SDL_GPA( "glDrawBuffer" );
    qglDrawElements              = SDL_GPA( "glDrawElements" );
    qglDrawPixels                = SDL_GPA( "glDrawPixels" );
    qglEdgeFlag                  = SDL_GPA( "glEdgeFlag" );
    qglEdgeFlagPointer           = SDL_GPA( "glEdgeFlagPointer" );
    qglEdgeFlagv                 = SDL_GPA( "glEdgeFlagv" );
    qglEnable                    = SDL_GPA( "glEnable" );
    qglEnableClientState         = SDL_GPA( "glEnableClientState" );
    qglEnd                       = SDL_GPA( "glEnd" );
    qglEndList                   = SDL_GPA( "glEndList" );
    qglEvalCoord1d               = SDL_GPA( "glEvalCoord1d" );
    qglEvalCoord1dv              = SDL_GPA( "glEvalCoord1dv" );
    qglEvalCoord1f               = SDL_GPA( "glEvalCoord1f" );
    qglEvalCoord1fv              = SDL_GPA( "glEvalCoord1fv" );
    qglEvalCoord2d               = SDL_GPA( "glEvalCoord2d" );
    qglEvalCoord2dv              = SDL_GPA( "glEvalCoord2dv" );
    qglEvalCoord2f               = SDL_GPA( "glEvalCoord2f" );
    qglEvalCoord2fv              = SDL_GPA( "glEvalCoord2fv" );
    qglEvalMesh1                 = SDL_GPA( "glEvalMesh1" );
    qglEvalMesh2                 = SDL_GPA( "glEvalMesh2" );
    qglEvalPoint1                = SDL_GPA( "glEvalPoint1" );
    qglEvalPoint2                = SDL_GPA( "glEvalPoint2" );
    qglFeedbackBuffer            = SDL_GPA( "glFeedbackBuffer" );
    qglFinish                    = SDL_GPA( "glFinish" );
    qglFlush                     = SDL_GPA( "glFlush" );
    qglFogf                      = SDL_GPA( "glFogf" );
    qglFogfv                     = SDL_GPA( "glFogfv" );
    qglFogi                      = SDL_GPA( "glFogi" );
    qglFogiv                     = SDL_GPA( "glFogiv" );
    qglFrontFace                 = SDL_GPA( "glFrontFace" );
    qglFrustum                   = SDL_GPA( "glFrustum" );
    qglGenLists                  = SDL_GPA( "glGenLists" );
    qglGenTextures               = SDL_GPA( "glGenTextures" );
    qglGetBooleanv               = SDL_GPA( "glGetBooleanv" );
    qglGetClipPlane              = SDL_GPA( "glGetClipPlane" );
    qglGetDoublev                = SDL_GPA( "glGetDoublev" );
    qglGetError                  = SDL_GPA( "glGetError" );
    qglGetFloatv                 = SDL_GPA( "glGetFloatv" );
    qglGetIntegerv               = SDL_GPA( "glGetIntegerv" );
    qglGetLightfv                = SDL_GPA( "glGetLightfv" );
    qglGetLightiv                = SDL_GPA( "glGetLightiv" );
    qglGetMapdv                  = SDL_GPA( "glGetMapdv" );
    qglGetMapfv                  = SDL_GPA( "glGetMapfv" );
    qglGetMapiv                  = SDL_GPA( "glGetMapiv" );
    qglGetMaterialfv             = SDL_GPA( "glGetMaterialfv" );
    qglGetMaterialiv             = SDL_GPA( "glGetMaterialiv" );
    qglGetPixelMapfv             = SDL_GPA( "glGetPixelMapfv" );
    qglGetPixelMapuiv            = SDL_GPA( "glGetPixelMapuiv" );
    qglGetPixelMapusv            = SDL_GPA( "glGetPixelMapusv" );
    qglGetPointerv               = SDL_GPA( "glGetPointerv" );
    qglGetPolygonStipple         = SDL_GPA( "glGetPolygonStipple" );
    qglGetString                 = SDL_GPA( "glGetString" );
    qglGetTexEnvfv               = SDL_GPA( "glGetTexEnvfv" );
    qglGetTexEnviv               = SDL_GPA( "glGetTexEnviv" );
    qglGetTexGendv               = SDL_GPA( "glGetTexGendv" );
    qglGetTexGenfv               = SDL_GPA( "glGetTexGenfv" );
    qglGetTexGeniv               = SDL_GPA( "glGetTexGeniv" );
    qglGetTexImage               = SDL_GPA( "glGetTexImage" );
    qglGetTexParameterfv         = SDL_GPA( "glGetTexParameterfv" );
    qglGetTexParameteriv         = SDL_GPA( "glGetTexParameteriv" );
    qglHint                      = SDL_GPA( "glHint" );
    qglIndexMask                 = SDL_GPA( "glIndexMask" );
    qglIndexPointer              = SDL_GPA( "glIndexPointer" );
    qglIndexd                    = SDL_GPA( "glIndexd" );
    qglIndexdv                   = SDL_GPA( "glIndexdv" );
    qglIndexf                    = SDL_GPA( "glIndexf" );
    qglIndexfv                   = SDL_GPA( "glIndexfv" );
    qglIndexi                    = SDL_GPA( "glIndexi" );
    qglIndexiv                   = SDL_GPA( "glIndexiv" );
    qglIndexs                    = SDL_GPA( "glIndexs" );
    qglIndexsv                   = SDL_GPA( "glIndexsv" );
    qglIndexub                   = SDL_GPA( "glIndexub" );
    qglIndexubv                  = SDL_GPA( "glIndexubv" );
    qglInitNames                 = SDL_GPA( "glInitNames" );
    qglInterleavedArrays         = SDL_GPA( "glInterleavedArrays" );
    qglIsEnabled                 = SDL_GPA( "glIsEnabled" );
    qglIsList                    = SDL_GPA( "glIsList" );
    qglIsTexture                 = SDL_GPA( "glIsTexture" );
    qglLightModelf               = SDL_GPA( "glLightModelf" );
    qglLightModelfv              = SDL_GPA( "glLightModelfv" );
    qglLightModeli               = SDL_GPA( "glLightModeli" );
    qglLightModeliv              = SDL_GPA( "glLightModeliv" );
    qglLightf                    = SDL_GPA( "glLightf" );
    qglLightfv                   = SDL_GPA( "glLightfv" );
    qglLighti                    = SDL_GPA( "glLighti" );
    qglLightiv                   = SDL_GPA( "glLightiv" );
    qglLineStipple               = SDL_GPA( "glLineStipple" );
    qglLineWidth                 = SDL_GPA( "glLineWidth" );
    qglListBase                  = SDL_GPA( "glListBase" );
    qglLoadIdentity              = SDL_GPA( "glLoadIdentity" );
    qglLoadMatrixd               = SDL_GPA( "glLoadMatrixd" );
    qglLoadMatrixf               = SDL_GPA( "glLoadMatrixf" );
    qglLoadName                  = SDL_GPA( "glLoadName" );
    qglLogicOp                   = SDL_GPA( "glLogicOp" );
    qglMap1d                     = SDL_GPA( "glMap1d" );
    qglMap1f                     = SDL_GPA( "glMap1f" );
    qglMap2d                     = SDL_GPA( "glMap2d" );
    qglMap2f                     = SDL_GPA( "glMap2f" );
    qglMapGrid1d                 = SDL_GPA( "glMapGrid1d" );
    qglMapGrid1f                 = SDL_GPA( "glMapGrid1f" );
    qglMapGrid2d                 = SDL_GPA( "glMapGrid2d" );
    qglMapGrid2f                 = SDL_GPA( "glMapGrid2f" );
    qglMaterialf                 = SDL_GPA( "glMaterialf" );
    qglMaterialfv                = SDL_GPA( "glMaterialfv" );
    qglMateriali                 = SDL_GPA( "glMateriali" );
    qglMaterialiv                = SDL_GPA( "glMaterialiv" );
    qglMatrixMode                = SDL_GPA( "glMatrixMode" );
    qglMultMatrixd               = SDL_GPA( "glMultMatrixd" );
    qglMultMatrixf               = SDL_GPA( "glMultMatrixf" );
    qglNewList                   = SDL_GPA( "glNewList" );
    qglNormal3b                  = SDL_GPA( "glNormal3b" );
    qglNormal3bv                 = SDL_GPA( "glNormal3bv" );
    qglNormal3d                  = SDL_GPA( "glNormal3d" );
    qglNormal3dv                 = SDL_GPA( "glNormal3dv" );
    qglNormal3f                  = SDL_GPA( "glNormal3f" );
    qglNormal3fv                 = SDL_GPA( "glNormal3fv" );
    qglNormal3i                  = SDL_GPA( "glNormal3i" );
    qglNormal3iv                 = SDL_GPA( "glNormal3iv" );
    qglNormal3s                  = SDL_GPA( "glNormal3s" );
    qglNormal3sv                 = SDL_GPA( "glNormal3sv" );
    qglNormalPointer             = SDL_GPA( "glNormalPointer" );
    qglOrtho                     = SDL_GPA( "glOrtho" );
    qglPassThrough               = SDL_GPA( "glPassThrough" );
    qglPixelMapfv                = SDL_GPA( "glPixelMapfv" );
    qglPixelMapuiv               = SDL_GPA( "glPixelMapuiv" );
    qglPixelMapusv               = SDL_GPA( "glPixelMapusv" );
    qglPixelStoref               = SDL_GPA( "glPixelStoref" );
    qglPixelStorei               = SDL_GPA( "glPixelStorei" );
    qglPixelTransferf            = SDL_GPA( "glPixelTransferf" );
    qglPixelTransferi            = SDL_GPA( "glPixelTransferi" );
    qglPixelZoom                 = SDL_GPA( "glPixelZoom" );
    qglPointSize                 = SDL_GPA( "glPointSize" );
    qglPolygonMode               = SDL_GPA( "glPolygonMode" );
    qglPolygonOffset             = SDL_GPA( "glPolygonOffset" );
    qglPolygonStipple            = SDL_GPA( "glPolygonStipple" );
    qglPopAttrib                 = SDL_GPA( "glPopAttrib" );
    qglPopClientAttrib           = SDL_GPA( "glPopClientAttrib" );
    qglPopMatrix                 = SDL_GPA( "glPopMatrix" );
    qglPopName                   = SDL_GPA( "glPopName" );
    qglPrioritizeTextures        = SDL_GPA( "glPrioritizeTextures" );
    qglPushAttrib                = SDL_GPA( "glPushAttrib" );
    qglPushClientAttrib          = SDL_GPA( "glPushClientAttrib" );
    qglPushMatrix                = SDL_GPA( "glPushMatrix" );
    qglPushName                  = SDL_GPA( "glPushName" );
    qglRasterPos2d               = SDL_GPA( "glRasterPos2d" );
    qglRasterPos2dv              = SDL_GPA( "glRasterPos2dv" );
    qglRasterPos2f               = SDL_GPA( "glRasterPos2f" );
    qglRasterPos2fv              = SDL_GPA( "glRasterPos2fv" );
    qglRasterPos2i               = SDL_GPA( "glRasterPos2i" );
    qglRasterPos2iv              = SDL_GPA( "glRasterPos2iv" );
    qglRasterPos2s               = SDL_GPA( "glRasterPos2s" );
    qglRasterPos2sv              = SDL_GPA( "glRasterPos2sv" );
    qglRasterPos3d               = SDL_GPA( "glRasterPos3d" );
    qglRasterPos3dv              = SDL_GPA( "glRasterPos3dv" );
    qglRasterPos3f               = SDL_GPA( "glRasterPos3f" );
    qglRasterPos3fv              = SDL_GPA( "glRasterPos3fv" );
    qglRasterPos3i               = SDL_GPA( "glRasterPos3i" );
    qglRasterPos3iv              = SDL_GPA( "glRasterPos3iv" );
    qglRasterPos3s               = SDL_GPA( "glRasterPos3s" );
    qglRasterPos3sv              = SDL_GPA( "glRasterPos3sv" );
    qglRasterPos4d               = SDL_GPA( "glRasterPos4d" );
    qglRasterPos4dv              = SDL_GPA( "glRasterPos4dv" );
    qglRasterPos4f               = SDL_GPA( "glRasterPos4f" );
    qglRasterPos4fv              = SDL_GPA( "glRasterPos4fv" );
    qglRasterPos4i               = SDL_GPA( "glRasterPos4i" );
    qglRasterPos4iv              = SDL_GPA( "glRasterPos4iv" );
    qglRasterPos4s               = SDL_GPA( "glRasterPos4s" );
    qglRasterPos4sv              = SDL_GPA( "glRasterPos4sv" );
    qglReadBuffer                = SDL_GPA( "glReadBuffer" );
    qglReadPixels                = SDL_GPA( "glReadPixels" );
    qglRectd                     = SDL_GPA( "glRectd" );
    qglRectdv                    = SDL_GPA( "glRectdv" );
    qglRectf                     = SDL_GPA( "glRectf" );
    qglRectfv                    = SDL_GPA( "glRectfv" );
    qglRecti                     = SDL_GPA( "glRecti" );
    qglRectiv                    = SDL_GPA( "glRectiv" );
    qglRects                     = SDL_GPA( "glRects" );
    qglRectsv                    = SDL_GPA( "glRectsv" );
    qglRenderMode                = SDL_GPA( "glRenderMode" );
    qglRotated                   = SDL_GPA( "glRotated" );
    qglRotatef                   = SDL_GPA( "glRotatef" );
    qglScaled                    = SDL_GPA( "glScaled" );
    qglScalef                    = SDL_GPA( "glScalef" );
    qglScissor                   = SDL_GPA( "glScissor" );
    qglSelectBuffer              = SDL_GPA( "glSelectBuffer" );
    qglShadeModel                = SDL_GPA( "glShadeModel" );
    qglStencilFunc               = SDL_GPA( "glStencilFunc" );
    qglStencilMask               = SDL_GPA( "glStencilMask" );
    qglStencilOp                 = SDL_GPA( "glStencilOp" );
    qglTexCoord1d                = SDL_GPA( "glTexCoord1d" );
    qglTexCoord1dv               = SDL_GPA( "glTexCoord1dv" );
    qglTexCoord1f                = SDL_GPA( "glTexCoord1f" );
    qglTexCoord1fv               = SDL_GPA( "glTexCoord1fv" );
    qglTexCoord1i                = SDL_GPA( "glTexCoord1i" );
    qglTexCoord1iv               = SDL_GPA( "glTexCoord1iv" );
    qglTexCoord1s                = SDL_GPA( "glTexCoord1s" );
    qglTexCoord1sv               = SDL_GPA( "glTexCoord1sv" );
    qglTexCoord2d                = SDL_GPA( "glTexCoord2d" );
    qglTexCoord2dv               = SDL_GPA( "glTexCoord2dv" );
    qglTexCoord2f                = SDL_GPA( "glTexCoord2f" );
    qglTexCoord2fv               = SDL_GPA( "glTexCoord2fv" );
    qglTexCoord2i                = SDL_GPA( "glTexCoord2i" );
    qglTexCoord2iv               = SDL_GPA( "glTexCoord2iv" );
    qglTexCoord2s                = SDL_GPA( "glTexCoord2s" );
    qglTexCoord2sv               = SDL_GPA( "glTexCoord2sv" );
    qglTexCoord3d                = SDL_GPA( "glTexCoord3d" );
    qglTexCoord3dv               = SDL_GPA( "glTexCoord3dv" );
    qglTexCoord3f                = SDL_GPA( "glTexCoord3f" );
    qglTexCoord3fv               = SDL_GPA( "glTexCoord3fv" );
    qglTexCoord3i                = SDL_GPA( "glTexCoord3i" );
    qglTexCoord3iv               = SDL_GPA( "glTexCoord3iv" );
    qglTexCoord3s                = SDL_GPA( "glTexCoord3s" );
    qglTexCoord3sv               = SDL_GPA( "glTexCoord3sv" );
    qglTexCoord4d                = SDL_GPA( "glTexCoord4d" );
    qglTexCoord4dv               = SDL_GPA( "glTexCoord4dv" );
    qglTexCoord4f                = SDL_GPA( "glTexCoord4f" );
    qglTexCoord4fv               = SDL_GPA( "glTexCoord4fv" );
    qglTexCoord4i                = SDL_GPA( "glTexCoord4i" );
    qglTexCoord4iv               = SDL_GPA( "glTexCoord4iv" );
    qglTexCoord4s                = SDL_GPA( "glTexCoord4s" );
    qglTexCoord4sv               = SDL_GPA( "glTexCoord4sv" );
    qglTexCoordPointer           = SDL_GPA( "glTexCoordPointer" );
    qglTexEnvf                   = SDL_GPA( "glTexEnvf" );
    qglTexEnvfv                  = SDL_GPA( "glTexEnvfv" );
    qglTexEnvi                  = SDL_GPA( "glTexEnvi" );
    qglTexEnviv                  = SDL_GPA( "glTexEnviv" );
    qglTexGend                   = SDL_GPA( "glTexGend" );
    qglTexGendv                  = SDL_GPA( "glTexGendv" );
    qglTexGenf                   = SDL_GPA( "glTexGenf" );
    qglTexGenfv                  = SDL_GPA( "glTexGenfv" );
    qglTexGeni                   = SDL_GPA( "glTexGeni" );
    qglTexGeniv                  = SDL_GPA( "glTexGeniv" );
    qglTexImage1D                = SDL_GPA( "glTexImage1D" );
    qglTexImage2D                = SDL_GPA( "glTexImage2D" );
    qglTexParameterf             = SDL_GPA( "glTexParameterf" );
    qglTexParameterfv            = SDL_GPA( "glTexParameterfv" );
    qglTexParameteri             = SDL_GPA( "glTexParameteri" );
    qglTexParameteriv            = SDL_GPA( "glTexParameteriv" );
    qglTexSubImage1D             = SDL_GPA( "glTexSubImage1D" );
    qglTexSubImage2D             = SDL_GPA( "glTexSubImage2D" );
    qglTranslated                = SDL_GPA( "glTranslated" );
    qglTranslatef                = SDL_GPA( "glTranslatef" );
    qglVertex2d                  = SDL_GPA( "glVertex2d" );
    qglVertex2dv                 = SDL_GPA( "glVertex2dv" );
    qglVertex2f                  = SDL_GPA( "glVertex2f" );
    qglVertex2fv                 = SDL_GPA( "glVertex2fv" );
    qglVertex2i                  = SDL_GPA( "glVertex2i" );
    qglVertex2iv                 = SDL_GPA( "glVertex2iv" );
    qglVertex2s                  = SDL_GPA( "glVertex2s" );
    qglVertex2sv                 = SDL_GPA( "glVertex2sv" );
    qglVertex3d                  = SDL_GPA( "glVertex3d" );
    qglVertex3dv                 = SDL_GPA( "glVertex3dv" );
    qglVertex3f                  = SDL_GPA( "glVertex3f" );
    qglVertex3fv                 = SDL_GPA( "glVertex3fv" );
    qglVertex3i                  = SDL_GPA( "glVertex3i" );
    qglVertex3iv                 = SDL_GPA( "glVertex3iv" );
    qglVertex3s                  = SDL_GPA( "glVertex3s" );
    qglVertex3sv                 = SDL_GPA( "glVertex3sv" );
    qglVertex4d                  = SDL_GPA( "glVertex4d" );
    qglVertex4dv                 = SDL_GPA( "glVertex4dv" );
    qglVertex4f                  = SDL_GPA( "glVertex4f" );
    qglVertex4fv                 = SDL_GPA( "glVertex4fv" );
    qglVertex4i                  = SDL_GPA( "glVertex4i" );
    qglVertex4iv                 = SDL_GPA( "glVertex4iv" );
    qglVertex4s                  = SDL_GPA( "glVertex4s" );
    qglVertex4sv                 = SDL_GPA( "glVertex4sv" );
    qglVertexPointer             = SDL_GPA( "glVertexPointer" );
    qglViewport                  = SDL_GPA( "glViewport" );

    // Extension functions (GL_ARB_multitexture, GL_EXT_compiled_vertex_array, GL_ATI_pn_triangles)
    qglActiveTextureARB          = SDL_GPA( "glActiveTextureARB" );
    qglClientActiveTextureARB    = SDL_GPA( "glClientActiveTextureARB" );
    qglMultiTexCoord2fARB        = SDL_GPA( "glMultiTexCoord2fARB" );
    qglLockArraysEXT             = SDL_GPA( "glLockArraysEXT" );
    qglUnlockArraysEXT           = SDL_GPA( "glUnlockArraysEXT" );
    qglPNTrianglesiATI           = SDL_GPA( "glPNTrianglesiATI" );
    qglPNTrianglesfATI           = SDL_GPA( "glPNTrianglesfATI" );

    // Check if critical functions loaded
    if ( !qglGetIntegerv ) {
        Com_Printf( "ERROR: Failed to load OpenGL functions via SDL_GL_GetProcAddress\n" );
        return qfalse;
    }

    return qtrue;
}
